### ISSUE TITLE
No Issues - just Feedback!

### ISSUE THREAD

**Issue by gnrmarcel** [notbluu/xbox-api#1]
Thanks for the script. I'm just learning JavaScript & Co. and hope that I can extract the name of the game and the link to the store besides the price

**Comment by 0x14307** [comment]
It could be possible, but currently this is very barebones. This uses a web scraper so if you can find a way to retrieve the URLs & put those into the prices (or by something else) then that would work instead.

**Comment by 0x14307** [comment]
I might also be planning to turn this into an actual API (with JSON parsing and all of that) so if I ever get to do that I'll let you know.

**Comment by gnrmarcel** [comment]
Sounds good!

**Comment by 0x14307** [comment]
I just pushed a commit that has a basic splice thing in it that grabs only the first one. It might not be much, but you can probably implement a for loop inside of it to keep it continuing .

**Comment by gnrmarcel** [comment]
thank you ... i will also have a look if there is a way to implement the "pagination" so that all offers can be queried
